//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_Extranet_Mock_WebApi_Rest.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GPContainer1 : DbContext
    {
        public GPContainer1()
            : base("name=GPContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mk_agendas> mk_agendas { get; set; }
        public DbSet<mk_listarCentrais> mk_listarCentrais { get; set; }
        public DbSet<mk_domicilios> mk_domicilios { get; set; }
        public DbSet<mk_lojas> mk_lojas { get; set; }
        public DbSet<mk_simulacao> mk_simulacao { get; set; }
    }
}
