//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_Extranet_Mock_WebApi_Rest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_lojas
    {
        public int lojasID { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> codEC { get; set; }
        public string descricao { get; set; }
        public Nullable<double> valorDisponivel { get; set; }
    }
}
