//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_Extranet_Mock_WebApi_Rest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mk_listarCentrais
    {
        public int listarCentraisID { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<int> codigoEc { get; set; }
        public string nome { get; set; }
        public string documento { get; set; }
        public string tipoPessoa { get; set; }
        public string tipoPagamento { get; set; }
        public Nullable<double> valorBruto { get; set; }
        public Nullable<double> valorBloqueado { get; set; }
        public Nullable<double> valorDisponivel { get; set; }
    }
}
